spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/vectorDB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:vectorDB}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:vectorDB}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:changeme}
jwt.expiration=86400000

fastapi.url=${FASTAPI_URL:http://api:8000}